### ISSUE TITLE
[Bug] Audio file doesn't play inside TagSpaces if file name gets too long

### ISSUE THREAD

**Issue by MarlQ** [tagspaces/viewerAudioVideo#2]
After adding too many tags, and the file name started exceeding a certain length (about 100), the .wav file could not be played inside the TagSpace application anymore.
It could still be played natively, however, and shortening the file name by removing tags made the file play again.

**Comment by uggrock** [comment]
we can not do much here, the limitation is the length of the file path, and apparently the nodejs which we use in background can not handle such long file names/paths. 100 tags is a lot, why not using the sidecar tagging method?
